defmodule PhoenixKitCatalogue.Schemas.Attribute do
  @moduledoc """
  Schema for attributes within an attribute group ("Color", "Trim").

  `key` is a stable slug unique within its group — the durable identity
  that translations can never change. It is generated by the context from
  the primary-language name at creation and never cast on update.

  `kind` semantics come from the product design: `"fixed"` = a single
  value shown on the product card; `"multi"` = a list of options, one of
  which is chosen downstream (per order line, in the parent app).
  """

  use Ecto.Schema
  use PhoenixKit.SchemaPrefix
  import Ecto.Changeset

  @type t :: %__MODULE__{}

  @primary_key {:uuid, UUIDv7, autogenerate: true}
  @foreign_key_type UUIDv7

  @kinds ~w(fixed multi)
  @statuses ~w(active archived)

  @spec allowed_kinds() :: [String.t()]
  def allowed_kinds, do: @kinds

  schema "phoenix_kit_cat_attributes" do
    field(:key, :string)
    field(:name, :string)
    field(:data, :map, default: %{})
    field(:kind, :string, default: "multi")
    field(:status, :string, default: "active")
    field(:position, :integer, default: 0)

    belongs_to(:group, PhoenixKitCatalogue.Schemas.AttributeGroup,
      foreign_key: :group_uuid,
      references: :uuid,
      type: UUIDv7
    )

    has_many(:values, PhoenixKitCatalogue.Schemas.AttributeValue,
      foreign_key: :attribute_uuid,
      references: :uuid,
      preload_order: [asc: :position]
    )

    timestamps(type: :utc_datetime)
  end

  def create_changeset(attribute, attrs) do
    attribute
    |> cast(attrs, [:group_uuid, :key, :name, :data, :kind, :status, :position])
    |> validate_required([:group_uuid, :key, :name])
    |> shared_validations()
    |> validate_format(:key, ~r/^[a-z0-9][a-z0-9_-]*$/)
    |> validate_length(:key, max: 100)
    |> unique_constraint(:key, name: :phoenix_kit_cat_attributes_group_key_index)
    |> foreign_key_constraint(:group_uuid)
  end

  # `key` is deliberately not castable after creation — it is the durable
  # identity future exclusion rules and order lines reference.
  def update_changeset(attribute, attrs) do
    attribute
    |> cast(attrs, [:name, :data, :kind, :status, :position])
    |> validate_required([:name])
    |> shared_validations()
  end

  defp shared_validations(changeset) do
    changeset
    |> validate_length(:name, min: 1, max: 255)
    |> validate_inclusion(:kind, @kinds)
    |> validate_inclusion(:status, @statuses)
  end
end
